name: Publish package to the Maven Central Repository

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }} # Value of the GPG private key to import
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase
      - name: Get POM version
        run: echo "POM_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Get tag version
        run: echo "TAG_VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
      - name: Make sure that the versions match
        run: '[[ "v$POM_VERSION" == "$TAG_VERSION" ]] && exit 0 || exit 1'

      - name: Publish package to maven central
        run: mvn --batch-mode clean compile javadoc:javadoc deploy -P release
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_CENTRAL_USER }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_PASSPHRASE }}
          MAVEN_OPTS: "--add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.text=ALL-UNNAMED --add-opens=java.desktop/java.awt.font=ALL-UNNAMED"

      - name: Deploy JavaDoc to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          clean: false
          folder: target/site/apidocs
          branch: javadoc
          target-folder: ${{ env.TAG_VERSION }}
      - name: Deploy JavaDoc to GitHub Pages - Latest
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          clean: true
          folder: target/site/apidocs
          branch: javadoc
          target-folder: latest
          force: true